# version: '3.8'
#MongoDB 5.0+ requires a CPU with AVX support, => sử dụng image: mongo:4.4
services:
  db-mongo:
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: nhathv73qb
      MONGO_INITDB_ROOT_PASSWORD: Nhathv041
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    expose:
      - 27017

  be-nest:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: unless-stopped
    environment:
      - PORT=6969
      - NODE_ENV=production
      - MONGO_URL=mongodb+srv://nhathv73qb:Nhathv041@cluster0.siqgjap.mongodb.net/jobs-dev
      # - DB_HOST=host.docker.internal
    expose:
      - 6969
    ports:
      - 6969:6969

volumes:
  mongodb:

    # docker compose -p nhathv-nest up -d
